spring.application.name=hogwartsV1
spring.datasource.url=jdbc:postgresql://localhost:5432/horwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl=update